In [2]:
from pyDOE import *


In [5]:
dm = ccdesign(2)
print(dm, len(dm))

[[-1.         -1.        ]
 [ 1.         -1.        ]
 [-1.          1.        ]
 [ 1.          1.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [-1.41421356  0.        ]
 [ 1.41421356  0.        ]
 [ 0.         -1.41421356]
 [ 0.          1.41421356]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]] 16


/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyDOE/doe_factorial.py:78: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rng = lvl*range_repeat


In [18]:
d2 = ccdesign(3, center=(0, 5), alpha='r', face='cci')
print(d2, len(d2))

[[-0.59460356 -0.59460356 -0.59460356]
 [ 0.59460356 -0.59460356 -0.59460356]
 [-0.59460356  0.59460356 -0.59460356]
 [ 0.59460356  0.59460356 -0.59460356]
 [-0.59460356 -0.59460356  0.59460356]
 [ 0.59460356 -0.59460356  0.59460356]
 [-0.59460356  0.59460356  0.59460356]
 [ 0.59460356  0.59460356  0.59460356]
 [-1.          0.          0.        ]
 [ 1.          0.          0.        ]
 [ 0.         -1.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.         -1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]] 19


/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyDOE/doe_factorial.py:78: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rng = lvl*range_repeat


In [16]:
import xlsxwriter

workbook = xlsxwriter.Workbook('arrays.xlsx')
worksheet = workbook.add_worksheet()

array = d2

row = 0

for col, data in enumerate(array):
    worksheet.write_column(row, col, data)

workbook.close()

In [27]:
t = ff2n(3)
t = t.transpose
print(t)

<built-in method transpose of numpy.ndarray object at 0x7f73b85e8a80>


/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyDOE/doe_factorial.py:78: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rng = lvl*range_repeat


In [23]:
workbook = xlsxwriter.Workbook('arrays.xlsx')
worksheet = workbook.add_worksheet()

array = d2

row = 0

for col, data in enumerate(t):
    worksheet.write_column(row, col, data)

workbook.close()

In [29]:
ff2n(3)

/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyDOE/doe_factorial.py:78: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rng = lvl*range_repeat


array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.]])